SisVetWeb/Controllers/ServicoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Domain.Entidades;
using Domain.Entidades.Cadastro;
using Repository;
using Repository.Context;
using Repository.Repositories;

namespace SisVetWeb.Controllers
{
    public class ServicoController : Controller
    {
        private ServicoRepository repoServico = new ServicoRepository();
        private TipoServicoRepository repoTipoServico = new TipoServicoRepository();
        private AtendimentoRepository repoAtendimento = new AtendimentoRepository();

        [ChildActionOnly]
        public ActionResult Index(int id)
        {
            ViewBag.AtendimentoID = id;
            var atendimentos = repoServico.GetAll().Where(a => a.AtendimentoId == id);
            return PartialView("_Index",atendimentos.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = repoServico.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return View(servico);
        }

        public ActionResult Create(int atendimentoID)
        {
            Servico servico = new Servico();
            servico.AtendimentoId = atendimentoID;
            ViewBag.TipoServicoID = new SelectList(repoTipoServico.GetAll(), "ID", "Descricao");
            return PartialView("_Create", servico);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,TipoServicoID,Valor,Observacao,AtendimentoID")] Servico servico,int tipoServicoId)
        {
            var tipoServico = new TipoServico();

            if (ModelState.IsValid)
            {
                using (var ctx = new BancoContexto())
                {
                    ctx.Entry(tipoServico).State = EntityState.Unchanged;
                    //servico.TipoServico = tipoServico;
                    ctx.Servicos.Add(servico);
                    ctx.SaveChanges();
                    return Json(new {success = true});
                }
                
            }
            
            return PartialView("_Create");
        }

        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = repoServico.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            ViewBag.AtendimentoID = new SelectList(repoAtendimento.GetAll(), "ID", "ID",servico.AtendimentoId);
            ViewBag.TipoServicoID = new SelectList(repoTipoServico.GetAll(), "ID", "Descricao", servico.TipoServicoId);
            return PartialView("_Edit",servico);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="ID,TipoServicoID,Valor,Observacao,AtendimentoID")] Servico servico)
        {
            if (ModelState.IsValid)
            {
                using (var ctx = new BancoContexto())
                {
                    
                    ctx.Entry(servico).State = EntityState.Modified;
                    await ctx.SaveChangesAsync();
                    return Json(new {success = true});
                }
            }
            ViewBag.AtendimentoID = new SelectList(repoAtendimento.GetAll(), "ID", "ID", servico.AtendimentoId);
            return PartialView("_Edit",servico);

        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Servico servico = repoServico.Find(id);
            if (servico == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete",servico);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Servico servico = repoServico.Find(id);
            repoServico.Excluir(x => x == servico);
            repoServico.SalvarTodos();
            return Json(new {success = true});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repoServico.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SisVetWeb/Views/Servico/Details.cshtml
@model Domain.Entidades.Cadastro.Servico

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Servico</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Atendimento.Situacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Atendimento.Situacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoServico.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoServico.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Observacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Observacao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SisVetWeb/Views/Servico/_Create.cshtml
@model Domain.Entidades.Cadastro.Servico

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Serviços</h4>
</div>


@using (Html.BeginForm()) 
{
    <div class="modal-body">
    @Html.AntiForgeryToken()
    
        <div class="form-horizontal">        
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.Label("Serviço", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TipoServicoID",(IEnumerable<SelectListItem>)ViewBag.TipoServicoID , new {@class = "form-control"})
                    @*@Html.DropDownList("TipoServicoID",(IEnumerable<SelectListItem>)ViewBag.TipoServicoID,"Selecione..." , new {@class = "form-control"})*@
                </div>
            </div>       

            <div class="form-group">
                @Html.Label("Descrição", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Observacao, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Observacao)
                </div>
            </div>
        </div>
    </div>
    
    <div class="modal-footer">
        <input class="btn btn-success" type="submit" value="Confirmar" />
        <button class="btn " data-dismiss="modal">Cancelar</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SisVetWeb/Views/Servico/_Delete.cshtml
@model Domain.Entidades.Cadastro.Servico

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Serviço</h4>
</div>

    @using (Html.BeginForm()) {
        <div class="modal-body">
            <h3>Deseja realmente excluir o registro?</h3>
            @Html.AntiForgeryToken()
        </div>
    
        <div class="modal-footer">
            <input class="btn btn-danger" type="submit" value="Excluir" />
            <button class="btn " data-dismiss="modal">Cancelar</button>
        </div>
    }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SisVetWeb/Views/Servico/_Edit.cshtml
@model Domain.Entidades.Cadastro.Servico

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Serviço</h4>
</div>

@using (Html.BeginForm())
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
    
        <div class="form-horizontal">
        
            @Html.ValidationSummary(true,"",new{@class = "text-danger"})
            @Html.HiddenFor(model => model.Id)
            
            <div style="display: none">
                @Html.DropDownList("AtendimentoID", String.Empty)
                @Html.ValidationMessageFor(model => model.AtendimentoId)
            </div>

            <div class="form-group">
                @Html.Label("Tipo Serviço", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("TipoServicoID", (IEnumerable<SelectListItem>)ViewBag.TipoServicoID,  new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TipoServicoId)

                </div>
            </div>

            <div class="form-group">
                @Html.Label("Descrição", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Observacao,new{@class ="form-control"})
                    @Html.ValidationMessageFor(model => model.Observacao)
                </div>
            </div>
           
        </div>
    </div>


    <div class="modal-footer">
        <input class="btn btn-success" type="submit" value="Confirmar" />
        <button class="btn " data-dismiss="modal">Cancelar</button>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SisVetWeb/Views/Servico/_Index.cshtml
@using SisVetWeb.Helpers
@model IEnumerable<Domain.Entidades.Cadastro.Servico>

<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Histórico de Serviços</strong>
    </div>
    <div>@Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span>", "Adicionar Serviço", "Create", "Servico", routeValues: new { AtendimentoID = ViewBag.AtendimentoID }, htmlAttributes: new { data_modal = "", @class = "btn btn-primary pull-right" })</div>
    <table class="table">
        <tr>
       
            <th>
                @Html.DisplayName("Serviço")
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoServico.Valor)
            </th>
          
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
      
            <td>
                @Html.DisplayFor(modelItem => item.TipoServico.Descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoServico.Valor)
            </td>
            
            <td>
                <div class="pull-right">
                    <div class="pull-right">
                        @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Editar", "Edit", "Servico", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-xs btn-default" })
                        &nbsp;
                        @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Excluir", "Delete", "Servico", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-xs btn-danger" })

                    </div>
                </div>
            </td>
        </tr>
        }

    </table>
</div>