SisVetWeb/Controllers/VacinacaoController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Domain.Entidades.Operacao;
using Domain.Entidades.Operacao.Vacinacao;
using Domain.EntidadesLeitura.WidGet;
using Repository.Context;
using Utils;
using Repository.Repositories;

namespace SisVetWeb.Controllers {
    public class VacinacaoController : Controller {
        private VacinacaoRepository repoVacinacao = new VacinacaoRepository();
        private BancoContexto db = new BancoContexto();
        private AnimalRepository repoAnimal = new AnimalRepository();
        private VacinaRepository repoVacina = new VacinaRepository();

        [ChildActionOnly]
        public ActionResult Index(int id) {
            ViewBag.AnimalID = id;
            var vacinacao = repoVacinacao.GetAll().Where(a => a.AnimalId == id);
            return PartialView("_Index", vacinacao.ToList());
        }

        public ActionResult WidGetListVacinacao() {
            //const int dezDias = 10;
            //var hoje = DateTime.Today;
            //var decimoDia = hoje.AddDays(dezDias);
            //var proximasVacinas = repoVacinacao.GetAll().Where(a => a.DataPrevisao >= hoje && a.DataPrevisao <= decimoDia && a.DataVacinacao == null);
            //return PartialView("WidGet/_WidGetListVacinacao", proximasVacinas.OrderBy(a => a.DataPrevisao).ToList());
            var listVacinacoes = (List<VacinacaoAVencerWidGet>)repoVacinacao.GetVacinacoesAVencerWidget();
            return PartialView("WidGet/_WidGetListVacinacao", SetMascaraTelefone(listVacinacoes));
        }

        public ActionResult WidGetListVacinacaoVencidas() {
            var vacinasVencidas = (List<VacinacaoVencidasWidGet>)repoVacinacao.GetVacinacoesVencidasWidget();
            return PartialView("WidGet/_WidGetListVacinacaoVencidas", SetMascaraTelefone(vacinasVencidas));
        }

        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacinacao vacinacao = repoVacinacao.Find(id);
            if (vacinacao == null) {
                return HttpNotFound();
            }
            return View(vacinacao);
        }

        public ActionResult Create(int AnimalID) {
            var vacinacao = new Vacinacao();
            vacinacao.AnimalId = AnimalID;
            ViewBag.VacinaId = new SelectList(repoVacina.GetAll().ToList(), "ID", "Descricao");
            ViewBag.AnimalId = new SelectList(repoAnimal.GetAll().ToList(), "ID", "Nome");
            return PartialView("_Create", vacinacao);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,DataPrevisao,DataVacinacao,VacinaId,AnimalId")] Vacinacao vacinacao) {
            if (ModelState.IsValid) {
                var vacina = repoVacina.Find(vacinacao.VacinaId);
                for (var dose = 1; dose <= vacina.Doses; dose++) {
                    if (dose == 1) {
                        vacinacao.DataPrevisao = DateTime.Now.Date;
                        vacinacao.DataVacinacao = DateTime.Now.Date;
                    } else {
                        vacinacao.DataPrevisao = DateTime.Now.Date.AddDays(vacina.IntervaloDias * (dose - 1));
                        vacinacao.DataVacinacao = null;

                    }
                    repoVacinacao.Adicionar(vacinacao);
                    repoVacinacao.SalvarTodos();
                }

                return Json(new { success = true });
            }


            return PartialView("_Create");
        }

        public async Task<ActionResult> Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacinacao vacinacao = await db.Vacinacoes.FindAsync(id);
            if (vacinacao == null) {
                return HttpNotFound();
            }
            ViewBag.AnimalId = new SelectList(repoAnimal.GetAll(), "ID", "Nome", vacinacao.AnimalId);
            ViewBag.VacinaId =
                repoVacina.GetAll()
                    .Select(
                        a =>
                            new SelectListItem() {
                                Text = a.Descricao,
                                Value = a.Id.ToString(),
                                Selected = a.Id == vacinacao.VacinaId
                            });
            return PartialView("_Edit", vacinacao);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,DataPrevisao,DataVacinacao,VacinaId,AnimalId")] Vacinacao vacinacao) {
            if (ModelState.IsValid) {
                using (var ctx = new BancoContexto()) {
                    ctx.Entry(vacinacao).State = EntityState.Modified;
                    await ctx.SaveChangesAsync();
                    return Json(new { success = true });
                }

            }
            return PartialView("_Edit", vacinacao);
        }

        public async Task<ActionResult> Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacinacao vacinacao = db.Vacinacoes.Find(id);
            if (vacinacao == null) {
                return HttpNotFound();
            }
            return PartialView("_Delete", vacinacao);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Vacinacao vacinacao = repoVacinacao.Find(id);
            repoVacinacao.Excluir(x => x == vacinacao);
            repoVacinacao.SalvarTodos();
            return Json(new { success = true });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                repoVacinacao.Dispose();
            }
            base.Dispose(disposing);
        }


        private List<VacinacaoVencidasWidGet> SetMascaraTelefone(List<VacinacaoVencidasWidGet> listVacinacaoVencidasWidGet) {
            try {
                for (var index = 0; index <= listVacinacaoVencidasWidGet.Count - 1; index++) {
                    listVacinacaoVencidasWidGet[index].NumeroTelefone =
                        listVacinacaoVencidasWidGet[index].NumeroTelefone.ApenasNumeros().FormatFone();
                }
            } catch (Exception) {
                throw;
            }
            return listVacinacaoVencidasWidGet;
        }

        private List<VacinacaoAVencerWidGet> SetMascaraTelefone(List<VacinacaoAVencerWidGet> listVacinacaoAVencerWidGet) {
            try {
                for (var index = 0; index <= listVacinacaoAVencerWidGet.Count - 1; index++) {
                    listVacinacaoAVencerWidGet[index].NumeroTelefone =
                        listVacinacaoAVencerWidGet[index].NumeroTelefone.ApenasNumeros().FormatFone();
                }
            } catch (Exception) {
                throw;
            }
            return listVacinacaoAVencerWidGet;
        }
    }
}

SisVetWeb/Views/Vacinacao/Details.cshtml
@model Domain.Entidades.Operacao.Vacinacao.Vacinacao

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Vacinacao</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Animal.Nome)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Animal.Nome)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Vacina.Descricao)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Vacina.Descricao)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DataPrevisao)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DataPrevisao)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DataVacinacao)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DataVacinacao)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

SisVetWeb/Views/Vacinacao/_Create.cshtml
@using System.Collections
@using Domain.Entidades.Operacao
@model Domain.Entidades.Operacao.Vacinacao.Vacinacao

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Vacina</h4>
</div>
@using (Html.BeginForm()) {
    <div class="modal-body">
    @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true)

            @*<div class="form-group">
        @Html.LabelFor(model => model.DataPrevisao, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataPrevisao)
            @Html.ValidationMessageFor(model => model.DataPrevisao)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DataVacinacao, new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DataVacinacao)
            @Html.ValidationMessageFor(model => model.DataVacinacao)
        </div>
    </div>
*@
            @*<div class="form-group" >
                @Html.LabelFor(model => model.AnimalId, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AnimalId", String.Empty)
                    @Html.ValidationMessageFor(model => model.AnimalId)
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.VacinaId, "Vacina", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("VacinaId",(IEnumerable<SelectListItem>) ViewBag.VacinaId,"Selecione",new{@class = "form-control ",required = true})
                    @Html.ValidationMessageFor(model => model.VacinaId)
                </div>
            </div>


        </div>
    </div>

    <div class="modal-footer">
        <input class="btn btn-success" type="submit" value="Confirmar" />
        <button class="btn" data-dismiss="modal">Cancelar</button>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}

SisVetWeb/Views/Vacinacao/_Delete.cshtml
@model Domain.Entidades.Operacao.Vacinacao.Vacinacao

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Vacina</h4>
</div>

@using (Html.BeginForm()) {
    <div class="modal-body">
        <h3>Deseja realmente excluir o registro?</h3>
        @Html.AntiForgeryToken()
    </div>

    <div class="modal-footer">
        <input class="btn btn-danger" type="submit" value="Excluir" />
        <button class="btn " data-dismiss="modal">Cancelar</button>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SisVetWeb/Views/Vacinacao/_Edit.cshtml
@model Domain.Entidades.Operacao.Vacinacao.Vacinacao

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="myModalLabel">Vacina</h4>
</div>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="modal-body">

        <div class="form-horizontal">

            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.DataPrevisao, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataPrevisao)
                    @Html.ValidationMessageFor(model => model.DataPrevisao)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DataVacinacao, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DataVacinacao)
                    @Html.ValidationMessageFor(model => model.DataVacinacao)
                </div>
            </div>

            <div class="form-group" style="display: none">
                @Html.LabelFor(model => model.VacinaId, "VacinaId", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("VacinaId", String.Empty)
                    @Html.ValidationMessageFor(model => model.VacinaId)
                </div>
            </div>
            <div class="form-group" style="display:none">
                @Html.LabelFor(model => model.AnimalId, "AnimalId", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("AnimalId", String.Empty)
                    @Html.ValidationMessageFor(model => model.AnimalId)
                </div>
            </div>
        </div>
    </div>

    <div class="modal-footer">
        <input class="btn btn-success" type="submit" value="Confirmar" />
        <button class="btn " data-dismiss="modal">Cancelar</button>
    </div>

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SisVetWeb/Views/Vacinacao/_Index.cshtml
@using SisVetWeb.Helpers
@model IEnumerable<Domain.Entidades.Operacao.Vacinacao.Vacinacao>

<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <strong>Histórico de Vacinação</strong>
    </div>

    <div>@Html.NoEncodeActionLink("<span class='glyphicon glyphicon-plus'></span>", "Lançar Vacina", "Create", "Vacinacao", routeValues: new { AnimalID = ViewBag.AnimalID }, htmlAttributes: new { data_modal = "", @class = "btn btn-primary pull-right" })</div>
    <table class="table">
        <tr>
       
            <th class="col-md-5">
                @Html.DisplayName("Vacina")
            </th>
            <th>
                @Html.DisplayName("Data Previsão")
            </th>
            <th>
                @Html.DisplayName("Data Vacinação")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr>
               
                <td class="col-md-5">
                    @Html.DisplayFor(modelItem => item.Vacina.Descricao)
                </td>
                <td>
                    @Html.FormatValue(Convert.ChangeType(item.DataPrevisao, typeof(object)),
                        "{0: dd/MM/yyyy}")
                </td>
                <td>
                    @Html.FormatValue(Convert.ChangeType(item.DataVacinacao, typeof(object)),
                        "{0: dd/MM/yyyy}")
                </td>
                <td>
                    <div class="pull-right">
                        <div class="pull-right">
                            @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-pencil'></span>", "Editar", "Edit", "Vacinacao", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-xs btn-default" })
                            &nbsp;
                            @Html.NoEncodeActionLink("<span class='glyphicon glyphicon-trash'></span>", "Excluir", "Delete", "Vacinacao", routeValues: new { id = item.Id }, htmlAttributes: new { data_modal = "", @class = "btn btn-xs btn-danger" })

                        </div>
                    </div>
                </td>
            </tr>
        }

    </table>
</div>