SisVetWeb/Controllers/CidadeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Entidades;
using Domain.Entidades.Cadastro.Localidade;
using PagedList;
using Repository;
using Repository.Context;
using Repository.Repositories;

namespace SisVetWeb.Controllers
{
    public class CidadeController : Controller
    {
        private CidadeRepository repoCidade = new CidadeRepository();

        // GET: /Cidade/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string typeSearch)
        {
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            var cidades = from m in repoCidade.GetAll().ToList()
                          select m;
            return View(cidades.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Cidade/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidade cidade = repoCidade.Find(id);
            if (cidade == null)
            {
                return HttpNotFound();
            }
            return View(cidade);
        }

        // GET: /Cidade/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Cidade/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Descricao,SiglaUnidadeFederativa")] Cidade cidade)
        {
            if (ModelState.IsValid)
            {
                repoCidade.Adicionar(cidade);
                repoCidade.SalvarTodos();
                return RedirectToAction("Index");
            }

            return View(cidade);
        }

        // GET: /Cidade/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidade cidade = repoCidade.Find(id);
            if (cidade == null)
            {
                return HttpNotFound();
            }
            return View(cidade);
        }

        // POST: /Cidade/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Descricao,SiglaUnidadeFederativa")] Cidade cidade)
        {
            if (ModelState.IsValid)
            {
              repoCidade.Atualizar(cidade);
                repoCidade.SalvarTodos();
                return RedirectToAction("Index");
            }
            return View(cidade);
        }

        // GET: /Cidade/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidade cidade = repoCidade.Find(id);
            if (cidade == null)
            {
                return HttpNotFound();
            }
            return View(cidade);
        }

        // POST: /Cidade/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cidade cidade = repoCidade.Find(id);
            repoCidade.Excluir(x => x == cidade);
            repoCidade.SalvarTodos();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repoCidade.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SisVetWeb/Controllers/EspecieController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Domain.Entidades.Cadastro;
using PagedList;
using Repository;
using Repository.Repositories;


namespace SisVetWeb.Controllers
{
    public class EspecieController : Controller
    {
        private readonly EspecieRepository repoEspecie = new EspecieRepository();

        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page) {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NomeParam = String.IsNullOrEmpty(sortOrder) ? "Nome_desc" : "";

            if (searchString != null) {
                page = 1;
            } else {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var especies = from m in repoEspecie.GetAll().ToList()
                           select m;
            if (!String.IsNullOrEmpty(searchString)) {
                especies = especies.Where(s => s.Descricao.ToUpper().Contains(searchString.ToUpper()));
            }

            int pageSize = 20;
            int pageNumber = (page ?? 1);

            return View(especies.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Especie especie = repoEspecie.Find(id);
            if (especie == null)
            {
                return HttpNotFound();
            }
            return View(especie);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,descricao")] Especie especie)
        {
            if (ModelState.IsValid)
            {
                repoEspecie.Adicionar(especie);
                repoEspecie.SalvarTodos();
                return RedirectToAction("Index");
            }

            return View(especie);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Especie especie = repoEspecie.Find(id);
            if (especie == null)
            {
                return HttpNotFound();
            }
            return View(especie);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,descricao")] Especie especie)
        {
            if (ModelState.IsValid)
            {
                repoEspecie.Atualizar(especie);
                repoEspecie.SalvarTodos();
                return RedirectToAction("Index");
            }
            return View(especie);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Especie especie = repoEspecie.Find(id);
            if (especie == null)
            {
                return HttpNotFound();
            }
            return View(especie);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Especie especie = repoEspecie.Find(id);
            repoEspecie.Excluir(e => e == especie);
            repoEspecie.SalvarTodos();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repoEspecie.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SisVetWeb/Controllers/RacaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Domain.Entidades;
using Domain.Entidades.Cadastro;
using PagedList;
using Repository.Context;
using Repository;
using Repository.Repositories;

namespace SisVetWeb.Controllers {
    public class RacaController : Controller {
        private RacaRepository repoRaca = new RacaRepository();
        private EspecieRepository repoEspecie = new EspecieRepository();

        public ActionResult Index(string ordenacao, string pesquisa, string tipoPesquisa, int pagina = 1) {

            int totalRegistros = 20;
            ViewBag.IdParam = ordenacao == "Id_Desc" ? "Id" : "Id_Desc";
            ViewBag.NomeParam = ordenacao == "Nome" ? "Nome_Desc" : "Nome";

            ViewBag.ordenacaoCorrente = ordenacao;
            ViewBag.tipoPesquisa = tipoPesquisa;
            ViewBag.pesquisaCorrente = pesquisa;

            var racas = from m in repoRaca.GetAll().ToList()
                        select m;

            if (!String.IsNullOrEmpty(pesquisa)) {
                racas = racas.Where(s => s.Descricao.ToUpper().Contains(pesquisa.ToUpper()));
            }

            switch (ordenacao) {
                case "Nome_Desc":
                    racas = racas.OrderByDescending(x => x.Descricao);
                    break;
                case "Nome":
                    racas = racas.OrderBy(x => x.Descricao);
                    break;
                case "Id_Desc":
                    racas = racas.OrderByDescending(x => x.Id);
                    break;
                default:
                    racas = racas.OrderBy(x => x.Id);
                    break;

            }

            var quantidadeRegistros = racas.Count();
            if (!string.IsNullOrEmpty(pesquisa) && quantidadeRegistros > 0)
                totalRegistros = quantidadeRegistros;


            return View(racas.ToPagedList(pagina, totalRegistros));
        }

        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raca raca = repoRaca.Find(id);
            if (raca == null) {
                return HttpNotFound();
            }
            return View(raca);
        }

        public ActionResult Create() {

            ViewBag.EspecieId = new SelectList(repoEspecie.GetAll(), "Id", "Descricao");
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descricao")] Raca raca, int especieId) {
            var especieID = new Especie() { Id = especieId };
            
            if (ModelState.IsValid) {

                using (var ctx = new BancoContexto()) {
                    ctx.Entry(especieID).State = EntityState.Unchanged;
                    raca.Especie = especieID;
                    ctx.Racas.Add(raca);
                    ctx.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            return View(raca);
        }
        
        public ActionResult Edit(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Raca raca = repoRaca.Find(id);
            if (raca == null) {
                return HttpNotFound();
            }
            ViewBag.Especies =
                repoEspecie.GetAll()
                    .Select(
                        g =>
                            new SelectListItem {
                                Text = g.Descricao,
                                Value = g.Id.ToString(),
                                Selected = raca.EspecieId == g.Id
                            });
            return View(raca);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descricao")] Raca raca, int especieId) {
            if (ModelState.IsValid) {
                using (var ctx = new BancoContexto()) {
                    raca.EspecieId = especieId;
                    ctx.Entry(raca).State = EntityState.Modified;
                    ctx.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(raca);
        }

        public ActionResult Delete(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Raca raca = repoRaca.Find(id);
            if (raca == null) {
                return HttpNotFound();
            }
            return View(raca);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Raca raca = repoRaca.Find(id);
            repoRaca.Excluir(c => c == raca);
            repoRaca.SalvarTodos();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                repoRaca.Dispose();
            }
            base.Dispose(disposing);
        }



    }



}

SisVetWeb/Controllers/VacinaController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Domain.Entidades.Cadastro;
using PagedList;
using Repository.Repositories;

namespace SisVetWeb.Controllers
{
    public class VacinaController : Controller
    {
        private readonly VacinaRepository repoVacina = new VacinaRepository();


        public ActionResult Index(string ordenacao, string pesquisa, string tipoPesquisa, int pagina = 1)
        {
            int totalRegistros = 20;
            ViewBag.IdParam = ordenacao == "Id" ? "Id_Desc" : "Id";
            ViewBag.NomeParam = ordenacao == "Nome" ? "Nome_Desc" : "Nome";

            ViewBag.ordenacaoCorrente = ordenacao;
            ViewBag.tipoPesquisa = tipoPesquisa;
            ViewBag.pesquisaCorrente = pesquisa;

            var vacinas = from m in repoVacina.GetAll().ToList()
                        select m;

            if (!String.IsNullOrEmpty(pesquisa)) {
                vacinas = vacinas.Where(s => s.Descricao.ToUpper().Contains(pesquisa.ToUpper()));
            }

            switch (ordenacao) {
                case "Nome_Desc":
                    vacinas = vacinas.OrderByDescending(x => x.Descricao);
                    break;
                case "Nome":
                    vacinas = vacinas.OrderBy(x => x.Descricao);
                    break;
                case "Id_Desc":
                    vacinas = vacinas.OrderByDescending(x => x.Id);
                    break;
                default:
                    vacinas = vacinas.OrderBy(x => x.Id);
                    break;

            }

            var quantidadeRegistros = vacinas.Count();
            if (!string.IsNullOrEmpty(pesquisa) && quantidadeRegistros > 0)
                totalRegistros = quantidadeRegistros;


            return View(vacinas.ToPagedList(pagina, totalRegistros));
        }
        public ActionResult Details(int? id) {
            if (id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacina vacina = repoVacina.Find(id);
            if (vacina == null) {
                return HttpNotFound();
            }
            return View(vacina);
        }

        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Descricao,IntervaloDias,Doses")] Vacina vacina)
        {
            if (ModelState.IsValid)
            {
                repoVacina.Adicionar(vacina);
               repoVacina.SalvarTodos();
                return RedirectToAction("Index");
            }

            return View(vacina);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacina vacina = repoVacina.Find(id);
            if (vacina == null)
            {
                return HttpNotFound();
            }
            return View(vacina);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Descricao,IntervaloDias,Doses")] Vacina vacina)
        {
            if (ModelState.IsValid)
            {
                repoVacina.Atualizar(vacina);
                repoVacina.SalvarTodos();
                return RedirectToAction("Index");
            }
            return View(vacina);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacina vacina = repoVacina.Find(id);
            if (vacina == null)
            {
                return HttpNotFound();
            }
            return View(vacina);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Vacina vacina = repoVacina.Find(id);
            repoVacina.Excluir(x => x.Id == vacina.Id);
            repoVacina.SalvarTodos();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                repoVacina.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SisVetWeb/Views/Shared/ConfirmacaoExclusao.cshtml
<div id="divExcluir" ></div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="deleteModalLabel">Exclusão</h4>
            </div>

            <div class="modal-body">
                <input type="hidden" />
                <p>Todos os registros associados a este será excluido.<br>Deseja excluir<em><strong>"<span></span>"</strong></em>&nbsp;?</p>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Confirmar</button>
            </div>

        </div>
    </div>
</div>

SisVetWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SisVet - Green Téc.</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/modalexclusao")
    @Styles.Render("~/Content/font-awesome")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container" style="height: 90%">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Anjos de Patas", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cadastros<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                            <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Animal", "Index", "Animal")</li>
                            <li>@Html.ActionLink("Espécie", "Index", "Especie")</li>
                            <li>@Html.ActionLink("Raça", "Index", "Raca")</li>
                            <li>@Html.ActionLink("Medicamento", "Index", "Medicamento")</li>
                            <li>@Html.ActionLink("Vacinas", "Index", "Vacina")</li>
                            <li>@Html.ActionLink("Tipo Telefone", "Index", "TipoTelefone")</li>
                            <li>@Html.ActionLink("Tipo Serviço", "Index", "TipoServico")</li>
                            <li>@Html.ActionLink("Município", "Index", "Cidade")</li>


                        </ul>
                    </li>
                    @*<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Operações<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>
                                <li>@Html.ActionLink("Atendimento", "Index", "Atendimento")</li>
                            </ul>
                        </li>*@

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Financeiro<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                            <li>@Html.ActionLink("Grupo Centro de Custo", "Index", "FinanceiroCentroDeCustoGrupo")</li>
                            <li>@Html.ActionLink("Centro de Custo", "Index", "FinanceiroCentroDeCusto")</li>
                            <li>@Html.ActionLink("Planos de Pagamento", "Index", "FinanceiroPlanoDePagamento")</li>
                            <li>@Html.ActionLink("Contas a Receber", "Index", "FinanceiroContasReceber")</li>
                            <li>@Html.ActionLink("Movimentações", "Index", "FinanceiroMovimentacaoCaixa")</li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                            <li>@Html.ActionLink("Clientes", "Clientes", "Reports")</li>
                            <li>@Html.ActionLink("Vacinações Detalhado", "VacinacoesDetalhado", "Reports")</li>
                            <li>@Html.ActionLink("Análise Vacinas Mensal", "AnaliseVacinasMensal", "Reports")</li>
                            <li>@Html.ActionLink("Contas a Receber", "FinanceiroContasReceber", "Reports")</li>
                            <li>@Html.ActionLink("Movimentações", "FinanceiroMovimentacoes", "Reports")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div id="div-principal-conteudo" class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/mascaras")
    @Scripts.Render("~/bundles/validacao")
    @Scripts.Render("~/bundles/utils")
    @RenderSection("scripts", required: false)
</body>
</html>