SisVetWeb/Models/ClienteViewModel.cs
using System.ComponentModel.DataAnnotations;
using Domain.Entidades.Cadastro.Contato;
using Domain.Entidades.Cadastro.Localidade;
using System;


namespace SisVetWeb.Models
{
    public class ClienteViewModel
    {
        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string CpfCnpj { get; set; }

        public string RgIe { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string TipoPessoa { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public DateTime DataNascimento { get; set; }

        public DateTime DataCadastro { get; set; }

        public string Email { get; set; }

        [Required(ErrorMessage = "Campo obrigatório!")]
        public string Sexo { get; set; }


        public string NumeroTelefone { get; set; }

        public virtual int TipoTelefoneId { get; set; }

        public string NumeroTelefoneContato { get; set; }

        public virtual int TipoTelefoneContatoId { get; set; }

        public string NumeroTelefoneContato2 { get; set; }

        public virtual int TipoTelefoneContato2Id { get; set; }


        [StringLength(50, MinimumLength = 2, ErrorMessage = "A Descrição deve ser entre 2 e 50 caracteres!")]
        public string Rua { get; set; }

        public string Cep { get; set; }

        public string Complemento { get; set; }
        
        public string Numero { get; set; }

        public int? CidadeId { get; set; }

    }

    //public class EnderecoViewModel
    //{
    //    public string Rua { get; set; }

    //    public string CEP { get; set; }

    //    public string Numero { get; set; }

    //    public string Complemento { get; set; } 

    //    public Cidade Cidade { get; set; }

    //}

    //public class TelefoneViewModel
    //{

    //}
}

SisVetWeb/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.Routing;
using Business.Cliente;
using Domain.Entidades.Cadastro;
using Domain.Entidades.Cadastro.Contato;
using Domain.Entidades.Cadastro.Localidade;
using Microsoft.Ajax.Utilities;
using PagedList;
using Repository.Repositories;
using SisVetWeb.Models;
using Utils;

namespace SisVetWeb.Controllers
{
    public class ClienteController : Controller
    {
        public ActionResult Index(string ordenacao, string pesquisa, string tipoPesquisa, int pagina = 1)
        {

            int totalRegistros = 20;
            ViewBag.IdParam = ordenacao == "Id" ? "Id_Desc" : "Id";
            ViewBag.NomeParam = ordenacao == "Nome" ? "Nome_Desc" : "Nome";

            ViewBag.ordenacaoCorrente = ordenacao;
            ViewBag.tipoPesquisa = tipoPesquisa;
            ViewBag.pesquisaCorrente = pesquisa;

            var clientes = new ClienteRepository().GetAllClientes(ordenacao, pesquisa, tipoPesquisa);

            var quantidadeRegistros = clientes.Count();
            if (!string.IsNullOrEmpty(pesquisa) && quantidadeRegistros > 0)
                totalRegistros = quantidadeRegistros;

            return View(clientes.ToPagedList(pagina, totalRegistros));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = new ClienteRepository().Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        public ActionResult DetailsOwnerAnimal(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Cliente cliente = new ClienteRepository().Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View("_DetailsOwnerAnimal", cliente);
        }

        public ActionResult Create()
        {
            ViewBag.TipoTelefoneID = new SelectList(new TipoTelefoneRepository().GetAll(), "ID", "Descricao");
            ViewBag.CidadeID = new SelectList(new CidadeRepository().GetAll().ToList().OrderBy(x => x.Descricao), "ID", "Descricao");
            return View();
        }


        [HttpPost]
        public ActionResult Create(ClienteViewModel clienteViewModel)
        {
            Endereco endereco = null;
            Telefone telefone = null;
            var telefonesList = new List<Telefone>();

            var cliente = new Cliente();
            cliente.Nome = clienteViewModel.Nome;
            cliente.CpfCnpj = clienteViewModel.CpfCnpj.ApenasNumeros();
            cliente.RgIe = clienteViewModel.RgIe;
            cliente.Sexo = clienteViewModel.Sexo;
            cliente.DataNascimento = clienteViewModel.DataNascimento;
            cliente.DataCadastro = DateTime.Now;
            cliente.Email = clienteViewModel.Email;
            cliente.TipoPessoa = clienteViewModel.TipoPessoa;

            if (!clienteViewModel.Rua.IsNullOrWhiteSpace() &&
                !clienteViewModel.CidadeId.ToString().IsNullOrWhiteSpace())
            {
                endereco = new Endereco();
                endereco.Cep = clienteViewModel.Cep;
                endereco.Logradouro = clienteViewModel.Rua;
                endereco.CidadeId = clienteViewModel.CidadeId;
                endereco.Numero = clienteViewModel.Numero;
                endereco.Complemento = clienteViewModel.Complemento;
            }


            
            if (!clienteViewModel.NumeroTelefone.IsNullOrWhiteSpace() &&
                !clienteViewModel.TipoTelefoneId.ToString().IsNullOrWhiteSpace())
            {
                telefone = new Telefone();
                telefone.Numero = clienteViewModel.NumeroTelefone.ApenasNumeros();
                telefone.TipoTelefoneId = clienteViewModel.TipoTelefoneId;
                telefonesList.Add(telefone);
            }

            if (!clienteViewModel.NumeroTelefoneContato.IsNullOrWhiteSpace() &&
               !clienteViewModel.TipoTelefoneContatoId.ToString().IsNullOrWhiteSpace())
            {
                telefone = new Telefone();
                telefone.Numero = clienteViewModel.NumeroTelefoneContato.ApenasNumeros();
                telefone.TipoTelefoneId = clienteViewModel.TipoTelefoneContatoId;
                telefonesList.Add(telefone);
            }

            if (!clienteViewModel.NumeroTelefoneContato2.IsNullOrWhiteSpace() &&
               !clienteViewModel.TipoTelefoneContato2Id.ToString().IsNullOrWhiteSpace())
            {
                telefone = new Telefone();
                telefone.Numero = clienteViewModel.NumeroTelefoneContato2.ApenasNumeros();
                telefone.TipoTelefoneId = clienteViewModel.TipoTelefoneContato2Id;
                telefonesList.Add(telefone);
            }

            var clienteId = ClienteBusiness.Save(cliente, endereco, telefonesList);
            var routeValues = new RouteValueDictionary();
            routeValues.Add("clienteId", clienteId);
            return RedirectToAction("Create", "Animal", routeValues);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var cliente = new ClienteRepository().Find(id);

            if (cliente == null)
            {
                return HttpNotFound();
            }
            var cpf = cliente.CpfCnpj.ApenasNumeros();
            cliente.CpfCnpj = cpf;
            return View(cliente);
        }

        [HttpPost]
        public ActionResult Edit(Cliente cliente)
        {
            var cpf = cliente.CpfCnpj.ApenasNumeros();
            cliente.CpfCnpj = cpf;
            var repoCliente = new ClienteRepository();
            repoCliente.Atualizar(cliente);
            repoCliente.SalvarTodos();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult Delete(int id)
        {
            if (ClienteBusiness.HaRegistrosFinanceiroDoCliente(id)){
                Response.StatusCode = (int)HttpStatusCode.Conflict;
                return Json("Cliente possui registros financeiros efetuados. Não permitido sua exclusão.", JsonRequestBehavior.AllowGet);
            }
            
            string mensagem;
            var cliente = new ClienteRepository().Excluir(id);
            mensagem = string.Format("{0} excluído com sucesso.", cliente.Nome);
            Response.StatusCode = (int)HttpStatusCode.OK;
            return Json(mensagem, JsonRequestBehavior.AllowGet);
        }


        public ActionResult ListaAnimaisPorCliente(int id, int? page, string currentFilter, string searchString)
        {
            var animaisCliente = new AnimalRepository().GetAll().Where(x => x.Cliente.Id == id).ToList();
            int pageSize = 20;
            int pageNumber = (page ?? 1);
            return View(animaisCliente.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Error(Exception ex){
            return View("Error");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                new ClienteRepository().Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SisVetWeb/Controllers/ReportsController.cs
using System;
using System.Web.Mvc;
using Domain.EntidadesLeitura.ReportsModel;
using Reports;
using Utils;
using FinanceiroContasReceberReport = Reports.FinanceiroContasReceberReport;

namespace SisVetWeb.Controllers
{
    public class ReportsController : Controller
    {
        public ActionResult VacinacoesDetalhado()
        {
            return View();
        }

        public ActionResult AnaliseVacinasMensal()
        {
            return View();
        }

        public ActionResult FinanceiroContasReceber()
        {
            return View();
        }

        public ActionResult FinanceiroMovimentacoes()
        {
            return View();
        }

        public ActionResult Clientes()
        {
            return View();
        }

        public ActionResult GetRelatorioVacinacoesDetalhado(DateTime? data, DateTime? datafinal, string status, string pesquisaTexto)
        {
            var rpt = new VacinacoesDetalhadoReport(data, datafinal, status, pesquisaTexto);
            rpt.BasePath = GetServerPath();
            rpt.Titulo = "Relatório de vacinações";
            rpt.ListaDeFiltros.Add("Data Inicial", data.IsValidDate());
            rpt.ListaDeFiltros.Add("Data Final", datafinal.IsValidDate());
            rpt.ListaDeFiltros.Add("Status", status);
            rpt.ListaDeFiltros.Add("Descrição", pesquisaTexto);
            rpt.ImprimirCabecalhoPadrao = true;
            rpt.ImprimirRodapePadrao = false;
            return File(rpt.GetOutput().GetBuffer(), "application/pdf");
        }

        public ActionResult GetRelatorioAnaliseMensalDeVacinas(DateTime? dataInicial, DateTime? datafinal, string descricaoVacina)
        {
            var rpt = new VacinasAnaliseMensalReport(dataInicial, datafinal, descricaoVacina);
            rpt.Titulo = "Análise de Vacinas Mensal";
            rpt.BasePath = GetServerPath();
            rpt.ListaDeFiltros.Add("Data Inicial", dataInicial.IsValidDate());
            rpt.ListaDeFiltros.Add("Data Final", datafinal.IsValidDate());
            rpt.ListaDeFiltros.Add("Descrição", descricaoVacina);
            rpt.ImprimirCabecalhoPadrao = true;
            rpt.ImprimirRodapePadrao = false;
            return File(rpt.GetOutput().GetBuffer(), "application/pdf");
        }

        public ActionResult GetRelatorioContasReceber(DateTime? datainicial, DateTime? datafinal, string status, string pesquisaTexto)
        {
            var rpt = new FinanceiroContasReceberReport(datainicial, datafinal, status, pesquisaTexto);
            rpt.ListaDeFiltros.Add("Status", status);
            rpt.ListaDeFiltros.Add("Data Inicial", datainicial.IsValidDate());
            rpt.ListaDeFiltros.Add("Data Final", datafinal.IsValidDate());
            rpt.ListaDeFiltros.Add("pesquisa", pesquisaTexto);
            rpt.BasePath = GetServerPath();
            rpt.Titulo = "Relatório de Contas a Receber";
            rpt.ImprimirCabecalhoPadrao = true;
            rpt.ImprimirRodapePadrao = false;
            return File(rpt.GetOutput().GetBuffer(), "application/pdf");
        }

        public ActionResult GetRelatorioFinanceiroMovimentacoes(DateTime? datainicial, DateTime? datafinal, string tipo, string pesquisaTexto)
        {
            var rpt = new FinanceiroMovimentacoesReport(datainicial, datafinal, tipo, pesquisaTexto);
            rpt.ListaDeFiltros.Add("Tipo", tipo);
            rpt.ListaDeFiltros.Add("Data Inicial", datainicial.IsValidDate());
            rpt.ListaDeFiltros.Add("Data Final", datafinal.IsValidDate());
            rpt.ListaDeFiltros.Add("pesquisa", pesquisaTexto);
            rpt.BasePath = GetServerPath();
            rpt.Titulo = "Relatório de Movimentações";
            rpt.ImprimirCabecalhoPadrao = true;
            rpt.ImprimirRodapePadrao = false;
            return File(rpt.GetOutput().GetBuffer(), "application/pdf");
        }

        public ActionResult GetRelatorioClientes(DateTime? datainicial, DateTime? datafinal, string pesquisaTexto)
        {
            var rpt = new ClientesReport(datainicial, datafinal, pesquisaTexto);
            rpt.ListaDeFiltros.Add("Data Inicial", datainicial.IsValidDate());
            rpt.ListaDeFiltros.Add("Data Final", datafinal.IsValidDate());
            rpt.ListaDeFiltros.Add("Pesquisa", pesquisaTexto);
            rpt.BasePath = GetServerPath();
            rpt.Titulo = "Relatório de Clientes";
            rpt.ImprimirCabecalhoPadrao = true;
            rpt.ImprimirRodapePadrao = false;
            return File(rpt.GetOutput().GetBuffer(), "application/pdf");
        }

        private string GetServerPath()
        {
            return Server.MapPath("~");
        }

        //public FileResult BaixarPDF(DateTime? data, DateTime? datafinal, string status, string pesquisaTexto)
        //{
        //    var rpt = GetRelatorio(data, datafinal, status, pesquisaTexto);
        //    return File(rpt.GetOutput().GetBuffer(), "application/pdf", "Documento.pdf");
        //}
    }
}

SisVetWeb/Views/Reports/AnaliseVacinasMensal.cshtml
@using SisVetWeb.Helpers
<link href="~/Content/relatorios.css" rel="stylesheet" />
<link href="~/Content/form-bootstrap-override.css" rel="stylesheet" />
<h1>Relatório de Análise de Vacinas Mensal</h1>
<form></form>
<div id="container">
    @using (Html.BeginForm("GetRelatorioAnaliseMensalDeVacinas", "Reports", FormMethod.Get))
    {
        <br />
        <label for="data" id="descricaoPeriodo">Período:</label>
        <input class="form-control input-sm form-override" id="data" name="dataInicial" type="date">
        <input class="form-control input-sm form-override" id="datafinal" name="datafinal" type="date">
        <br />
    <input type="text" class="form-control" name="descricaoVacina" id="pesquisaTexto" placeholder="Pesquise pelo nome da vacina" />
        <hr />
        <button type="submit" class="btn btn-primary input-lg">Gerar Relatório</button>
    }
</div>

SisVetWeb/Views/Reports/Clientes.cshtml
@using SisVetWeb.Helpers
<link href="~/Content/relatorios.css" rel="stylesheet" />
<link href="~/Content/form-bootstrap-override.css" rel="stylesheet" />
<h1>Relatório de Clientes</h1>
<form></form>
<div id="container">
    @using (Html.BeginForm("GetRelatorioClientes", "Reports", FormMethod.Get))
    {
        <input type="text" class="form-control" name="pesquisaTexto" id="pesquisaTexto" placeholder="Pesquise por nome ou id" />
        <br/>
         <label for="datainicial" id="descricaoPeriodo">Período de Cadastro</label>
        <input class="form-control input-sm form-override" id="datainicial" name="datainicial" type="date">
        <input class="form-control input-sm form-override" id="datafinal" name="datafinal" type="date">
        <hr />
        <button type="submit" class="btn btn-primary input-lg">Gerar Relatório</button>
    }
</div>

SisVetWeb/Views/Reports/FinanceiroContasReceber.cshtml
@using SisVetWeb.Helpers
<link href="~/Content/relatorios.css" rel="stylesheet" />
<link href="~/Content/form-bootstrap-override.css" rel="stylesheet" />
<h1>Relatório de Contas a Receber</h1>
<form></form>
<div id="container">
    @using (Html.BeginForm("GetRelatorioContasReceber", "Reports", FormMethod.Get))
    {
        <label for="status">Situação:</label>
        @Html.DropDownList("status",
                    new List<SelectListItem>{
                        new SelectListItem{Text = "Abertas", Value = "Abertas", Selected = true},
                        new SelectListItem{Text = "Recebidas", Value = "Recebidas"},
                        new SelectListItem{Text = "Vencidas", Value = "Vencidas"},
                        new SelectListItem{Text = "Todas", Value = "Todas"}
                    }, new { @class = "form-control input-sm form-override", id = "status" })

        <br />
        <label for="datainicial" id="descricaoPeriodo"></label>
        <input class="form-control input-sm form-override" id="datainicial" name="datainicial" type="date">
        <input class="form-control input-sm form-override" id="datafinal" name="datafinal" type="date">
        <br />
        <input type="text" class="form-control" name="pesquisaTexto" id="pesquisaTexto" placeholder="Pesquise por nome do cliente ou centro de custo" />
        <hr />
        <button type="submit" class="btn btn-primary input-lg">Gerar Relatório</button>
    }
</div>

<script>

    $(document).ready(function () {
        $('#descricaoPeriodo').html('Emissão:');
    });

    $('select').on('change', function () {
        if (this.value == "Vencidas") {
            $('#descricaoPeriodo').html('Vencimento:');
        } else if (this.value == "Abertas") {
            $('#descricaoPeriodo').html('Emissão:');
        } else if (this.value == "Recebidas") {
            $('#descricaoPeriodo').html('Recebimento:');
        }
        else {
            $("#descricaoPeriodo").html('Emissão');
        }
    });
</script>

SisVetWeb/Views/Reports/FinanceiroMovimentacoes.cshtml
@using SisVetWeb.Helpers
<link href="~/Content/relatorios.css" rel="stylesheet" />
<link href="~/Content/form-bootstrap-override.css" rel="stylesheet" />
<h1>Relatório de Movimentações</h1>
<form></form>
<div id="container">
    @using (Html.BeginForm("GetRelatorioFinanceiroMovimentacoes", "Reports", FormMethod.Get))
    {
        <label for="tipo">Tipo:</label>
        @Html.DropDownList("tipo",
                    new List<SelectListItem>{
                        new SelectListItem{Text = "Crédito", Value = "Credito", Selected = true},
                        new SelectListItem{Text = "Débito", Value = "Debito"},
                        new SelectListItem{Text = "Todas", Value = "Todas"},
                    }, new { @class = "form-control input-sm form-override", id = "tipo" })

        <br />
        <label for="datainicial" id="descricaoPeriodo">Período:</label>
        <input class="form-control input-sm form-override" id="datainicial" name="datainicial" type="date">
        <input class="form-control input-sm form-override" id="datafinal" name="datafinal" type="date">
        <br />
        <input type="text" class="form-control" name="pesquisaTexto" id="pesquisaTexto" placeholder="Pesquise por centro de custo" />
        <hr />
        <button type="submit" class="btn btn-primary input-lg">Gerar Relatório</button>
    }
</div>

SisVetWeb/Views/Reports/Vacinacoes.cshtml
@using SisVetWeb.Helpers
<link href="~/Content/relatorios.css" rel="stylesheet" />
<link href="~/Content/form-bootstrap-override.css" rel="stylesheet" />
<h1>Relatório de Vacinações</h1>
<form></form>
<div id="container">
    @using (Html.BeginForm("Preview", "Reports", FormMethod.Get))
    {
        <label class="radio-inline">
            <input type="radio" id="check-vencidas" name="status" class="check" value="Vencidas" checked>
            Vencidas
        </label>
        <br />
        <label class="radio-inline">
            <input type="radio" name="status" class="check" value="Vencer">
            A vencer
        </label>
        <br />
        <label class="radio-inline">
            <input type="radio" name="status" class="check" value="Aplicadas">
            Aplicadas
        </label>

        <br />
        <label for="data" id="descricaoPeriodo" >Vencimento até:</label>
        <input class="form-control input-sm form-override" id="data" name="data" type="date">
        <input class="form-control input-sm form-override" id="datafinal" name="datafinal" type="date">
        <br />
        <input type="text" class="form-control" name="pesquisaTexto" id="pesquisaTexto" placeholder="Pesquise por nome do cliente ou animal" />
        <hr />
        <button type="submit" class="btn btn-primary input-lg">Gerar Relatório</button>
    }
</div>

<script>
    
    $(document).ready(function () {
        $('#descricaoPeriodo').html('Vencidas apartir de:');
        $('#check-vencidas').prop('checked', 'true');
        $('#datafinal').css('display', 'none');
    });
    
    $('.check').click(function (e) {
        if (e.currentTarget.defaultValue == "Vencer") {
            $('#descricaoPeriodo').html('Vencimento até:');
            $('#datafinal').css('display', 'none');
        } else if (e.currentTarget.defaultValue == "Vencidas") {
            $('#descricaoPeriodo').html('Vencidas apartir de:');
            $('#datafinal').css('display', 'none');
        } else {
            $('#datafinal').css('display', 'inline');
            $("#descricaoPeriodo").html('Intervalo de:');
        }
    });
</script>

SisVetWeb/Views/Reports/VacinacoesDetalhado.cshtml
@using SisVetWeb.Helpers
<link href="~/Content/relatorios.css" rel="stylesheet" />
<link href="~/Content/form-bootstrap-override.css" rel="stylesheet" />
<h1>Relatório de Vacinações</h1>
<form></form>
<div id="container">
    @using (Html.BeginForm("GetRelatorioVacinacoesDetalhado", "Reports", FormMethod.Get))
    {
        <label class="radio-inline">
            <input type="radio" id="check-vencidas" name="status" class="check" value="Vencidas" checked>
            Vencidas
        </label>
        <br />
        <label class="radio-inline">
            <input type="radio" name="status" class="check" value="Vencer">
            A vencer
        </label>
        <br />
        <label class="radio-inline">
            <input type="radio" name="status" class="check" value="Aplicadas">
            Aplicadas
        </label>

        <br />
        <label for="data" id="descricaoPeriodo" >Vencimento até:</label>
        <input class="form-control input-sm form-override" id="data" name="data" type="date">
        <label id="label" style="color: tomato; font-weight: lighter"></label>
        <input class="form-control input-sm form-override" id="datafinal" name="datafinal" type="date">
        <br />
        <input type="text" class="form-control" name="pesquisaTexto" id="pesquisaTexto" placeholder="Pesquise por nome do cliente, animal ou vacina" />
        <hr />
        <button type="submit" class="btn btn-primary input-lg">Gerar Relatório</button>
    }
</div>

<script>
    
    $(document).ready(function () {
        $('#descricaoPeriodo').html('Vencidas apartir de:');
        $('#label').html('<span style="color:#20b2aa; font-weight: lighter">Obs:</span> Utilizar data MENOR que a atual.');
        $('#check-vencidas').prop('checked', 'true');
        $('#datafinal').css('display', 'none');
        $('#label').css('display', 'inline');
    });
    
    $('.check').click(function (e) {
        if (e.currentTarget.defaultValue == "Vencer") {
            $('#descricaoPeriodo').html('Vencimento até:');
            $('#datafinal').css('display', 'none');
            $('#label').html('<span style="color:#20b2aa; font-weight: lighter">Obs:</span> Utilizar data MAIOR que a atual.');
            $('#label').css('display', 'inline');
        } else if (e.currentTarget.defaultValue == "Vencidas") {
            $('#descricaoPeriodo').html('Vencidas apartir de:');
            $('#datafinal').css('display', 'none');
            $('#label').html('<span style="color:#20b2aa; font-weight: lighter">Obs:</span> Utilizar data MENOR que a atual.');
            $('#label').css('display', 'inline');
        } else {
            $('#datafinal').css('display', 'inline');
            $('#label').css('display', 'none');
            $("#descricaoPeriodo").html('Intervalo de:');
        }
    });
</script>